### ISSUE TITLE
NameError: name '__get_column_types' is not defined 

### ISSUE THREAD

**Issue by aalejoramirezz** [Esri/insights-scripting-guide#6]
hi there,

I  am using the magic command %insights_return(df) to add an Pandas dateframe but I received this error after  running the cell:
**NameError: name '__get_column_types' is not defined** 

What am I doing wrong?

Thanks very much

**Comment by applecool** [comment]
@aalejoramirezz Hi, Seems like you have some missing libraries. You might be missing msgpack. Please install msgpack as part of your setup. That should fix the issue.

**Comment by applecool** [comment]
@aalejoramirezz I have updated the instructions on the conda in the readme. Please take a look :) Thanks.

**Comment by aalejoramirezz** [comment]
thanks for replying @applecool 
I tried: **conda install -c conda-forge msgpack**   and failed
So I did:  **conda install msgpack-python**    and works.

But still getting the same errors :(
**NameError: name '__get_column_types' is not defined**
**NameError: name 'insights_dict' is not defined**

**Comment by phpmaps** [comment]
@aalejoramirezz I can make this change.  I too see same behavior. 

 Are you using Mac or Windows?

**Comment by aalejoramirezz** [comment]
@phpmaps hi, I'm using Windows and Anaconda

**Comment by applecool** [comment]
@aalejoramirezz That's right its `msgpack-python` on conda. I updated that as well. Do you have shapely and geopandas installed? 
These are the required libs - `pandas`, `geopandas`, `numpy`, `matplotlib`, `msgpack`, `shapely` and `requests`. 

Try `conda list` and check if you have all these packages exist in the list. That will give you an idea if you are missing any packages mentioned above.

**Comment by aalejoramirezz** [comment]
@applecool Yeah, I already installed all of them.
**Versions**
shapely 1.6.4,  geopandas 0.6.1, pandas 0.25.1, numpy 1.16.5,
matplot 3.1.1, msgpack-python 0.6.1 , requests 2.22.0

The error still persists

**Comment by jnbaene** [comment]
Hello, any update on this error?

> thanks for replying @applecool
> I tried: **conda install -c conda-forge msgpack** and failed
> So I did: **conda install msgpack-python** and works.
> 
> But still getting the same errors :(
> **NameError: name '__get_column_types' is not defined**
> **NameError: name 'insights_dict' is not defined**

I´m also getting the "NameError: name 'insights_dict' is not defined" 
I alsho vae installed all the libraries that @applecool  lists.

Thanks

**Comment by applecool** [comment]
@jnbaene That is strange. Which version of Insights are you using currently? And is it desktop or enterprise?

**Comment by jnbaene** [comment]
@applecool I'm using Insights Desktop

**Comment by jnbaene** [comment]
Hello @applecool , I have an update with this issue.
Just created a new environment  from scratch and tried doing the same action, viewing a variable with the script and it worked. I've checked what were the differences between both environments and found 12 packages that weren't present on my original environment, so maybe some of them could cause this issue to pop up. I will list them and hope it helps

# Name | Version | Build | Channel
-- | -- | -- | --
asn1crypto | 1.2.0 | py37_0 | anaconda
deprecated | 1.2.7 | pypi_0 | pypi
descartes | 1.1.0 | pypi_0 | pypi
joblib | 0.14.0 | pypi_0 | pypi
palettable | 3.3.0 | pypi_0 | pypi
pandoc | 2.2.3.2 | 0 | anaconda
pysal | 2.1.0 | pypi_0 | pypi
scikit-learn | 0.21.3 | pypi_0 | pypi
scipy | 1.3.3 | pypi_0 | pypi
seaborn | 0.9.0 | pypi_0 | pypi
tqdm | 4.39.0 | pypi_0 | pypi
wrapt | 1.11.2 | pypi_0 | pypi
